import Phaser from "phaser";
import { loadManifest } from "./manifest";
import { withFallback } from "./placeholder";
import { chooseCharacter } from "./select";
import { WorldScene } from "./scenes/WorldScene";
import { loadWorld } from "./maps";
import { MapPreviewScene } from "./scenes/MapPreviewScene";

async function bootMapPreview(): Promise<boolean> {
  if (location.hash !== "#map") return false;
  const world = await loadWorld();
  if (!world) {
    document.body.innerHTML =
      '<p style="color:#eef;font-family:monospace;padding:2rem">No map yet ' +
      "(pixel/maps/world/world.json not found).</p>";
    return true;
  }
  const game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: "game",
    backgroundColor: "#12121c",
    pixelArt: true,
    scale: { mode: Phaser.Scale.RESIZE, width: window.innerWidth, height: window.innerHeight },
    scene: [MapPreviewScene],
  });
  game.registry.set("world", world);
  return true;
}

/** Tiny build-version badge so testers can tell which deploy they're running. */
function showVersion() {
  const sha = (import.meta.env.VITE_GIT_SHA as string | undefined) || "dev";
  console.log(`[nangijala] build ${sha}`);
  const el = document.createElement("div");
  el.textContent = sha.slice(0, 7);
  el.style.cssText =
    "position:fixed;left:6px;bottom:4px;z-index:50;font:11px monospace;color:#8890b3;" +
    "opacity:.7;pointer-events:none;user-select:none";
  document.body.appendChild(el);
}

/** Poll /version and offer a one-click reload when a newer deploy is live. */
function watchForUpdates() {
  const mine = (import.meta.env.VITE_GIT_SHA as string | undefined) || "dev";
  if (mine === "dev") return; // local dev: vite HMR handles it
  const check = async () => {
    try {
      const res = await fetch("/version", { cache: "no-store" });
      if (!res.ok) return;
      const { sha } = (await res.json()) as { sha: string };
      if (sha && sha !== "dev" && sha !== mine) showUpdateBanner(sha);
    } catch {}
  };
  setInterval(check, 60_000);
}

let updateBannerShown = false;
function showUpdateBanner(sha: string) {
  if (updateBannerShown) return;
  updateBannerShown = true;
  const el = document.createElement("div");
  el.textContent = `⬆ New version ${sha.slice(0, 7)} — click to reload`;
  el.style.cssText =
    "position:fixed;top:10px;left:50%;transform:translateX(-50%);z-index:100;cursor:pointer;" +
    "padding:8px 16px;border-radius:8px;background:#5a7bd6;color:#fff;font:14px system-ui,sans-serif;" +
    "box-shadow:0 4px 16px #0007";
  el.addEventListener("click", () => location.reload());
  document.body.appendChild(el);
}

/** Per-variant tile art bases (client/public/tile-bases.json, generated by
 * scripts/build-tile-bases.mjs at manifest time) — how deep each variant's
 * drawn content reaches, so tall art can be grounded exactly. Null when the
 * file is missing; the scenes fall back to the old imgH-64 lift. */
async function loadTileBases(): Promise<unknown> {
  try {
    const res = await fetch("/tile-bases.json");
    if (res.ok) return await res.json();
  } catch {}
  return null;
}

/** The emission demo world ([0] in game / #emission): every glowing
 * tile variant on a numbered station under the full night pipeline. */
async function bootEmissionDemo(): Promise<boolean> {
  if (location.hash !== "#emission") return false;
  const { EmissionDemoScene } = await import("./scenes/EmissionDemoScene");
  let emission = {};
  try {
    const res = await fetch("/assets/tiles/emission.json");
    if (res.ok) emission = ((await res.json()) as { categories?: object }).categories ?? {};
  } catch {}
  const tileBases = await loadTileBases();
  const game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: "game",
    backgroundColor: "#090911",
    pixelArt: true,
    scale: { mode: Phaser.Scale.RESIZE, width: window.innerWidth, height: window.innerHeight },
    scene: [EmissionDemoScene],
  });
  game.registry.set("emission", emission);
  game.registry.set("tileBases", tileBases);
  return true;
}

async function boot() {
  showVersion();
  watchForUpdates();
  if (await bootEmissionDemo()) return;
  if (await bootMapPreview()) return;
  const manifest = await loadManifest();
  // The art agents periodically reset/regenerate the roster, so it can be empty.
  // Never dead-end the player: fall back to a built-in "Wanderer" so the shared
  // world is always joinable (the world scene draws it procedurally).
  manifest.characters = withFallback(manifest.characters);

  // The isometric tile world (may be null if the maps submodule isn't present;
  // the world scene falls back to a plain ground in that case).
  const world = await loadWorld();
  const tileBases = await loadTileBases();

  // Pre-join screen: pick any generated character + a name, then enter the world.
  const { character, name } = await chooseCharacter(manifest);

  const game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: "game",
    backgroundColor: "#12121c",
    pixelArt: true,
    scale: {
      mode: Phaser.Scale.RESIZE,
      width: window.innerWidth,
      height: window.innerHeight,
    },
    scene: [WorldScene],
  });

  game.registry.set("manifest", manifest);
  game.registry.set("character", character);
  game.registry.set("name", name);
  game.registry.set("world", world);
  game.registry.set("tileBases", tileBases);
}

boot();
