"""Delete tiles this domain generated but did NOT keep, so PixelLab does not fill
with junk from regeneration.

Why this needs to be careful rather than clever
-----------------------------------------------
tiles2's `sync.py` DROPS any local sheet whose PixelLab tile_id 404s — that is a
feature (delete-in-UI to force a re-roll), but it means deleting the wrong id here
would silently delete shipped art from the repo on the next tiles2 run. There are
currently 905 tiles-pro on the account and only a handful are ours.

So this refuses to delete anything unless it is BOTH:

  1. in our own registry (`tiles/generated.json`) — every id this domain created,
     written at generation time. Anything not in it is someone else's: the
     maintainer's own experiments, tiles2's shipped sheets, another domain's work.
     Never touched, never even considered.
  2. not currently referenced anywhere in the repo — a second, independent check
     against the filesystem, so a registry mistake still cannot delete live art.

Dry-run is the default; `--apply` is required to delete. Deletions are irreversible.

  python tiles/pipeline/pixellab_gc.py                 # show what WOULD be deleted
  python tiles/pipeline/pixellab_gc.py --apply         # delete rejected + unreferenced
  python tiles/pipeline/pixellab_gc.py --keep <id> ... # mark ids as approved
  python tiles/pipeline/pixellab_gc.py --reject <id> ... # mark rejected (deleted on next --apply)
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess

from pixellab_client import PixelLabClient, PixelLabError

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(ROOT)
REGISTRY = os.path.join(ROOT, "generated.json")


def _now():
    return datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")


def load():
    if os.path.isfile(REGISTRY):
        with open(REGISTRY) as f:
            return json.load(f)
    return {"schema": "tiles3/generated@1", "items": {}}


def save(reg):
    with open(REGISTRY, "w") as f:
        json.dump(reg, f, indent=2, sort_keys=True)


def record(tile_id, purpose, prompt="", status="pending"):
    """Register an id at generation time. Called by whatever generates, so the GC
    can only ever see — and therefore only ever delete — our own work."""
    if not tile_id:
        return
    reg = load()
    reg["items"][tile_id] = {"purpose": purpose, "prompt": prompt[:400],
                             "status": status, "created": _now()}
    save(reg)


def set_status(ids, status):
    reg = load()
    n = 0
    for i in ids:
        if i in reg["items"]:
            reg["items"][i]["status"] = status
            reg["items"][i]["reviewed"] = _now()
            n += 1
        else:
            print(f"  ! not ours, ignoring: {i}")
    save(reg)
    return n


def referenced_ids():
    """Every tile_id mentioned anywhere in the repo's tracked files. The independent
    safety net: if art derived from an id is still committed, the id is in use, no
    matter what the registry believes."""
    try:
        out = subprocess.run(
            ["git", "grep", "-hoE", r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"],
            cwd=REPO, capture_output=True, text=True, timeout=180).stdout
        return set(out.split())
    except Exception as e:
        raise PixelLabError(f"could not scan the repo for referenced ids ({e}); "
                            "refusing to delete without that check")


def main():
    ap = argparse.ArgumentParser(description="Delete unused tiles 3.0 generations from PixelLab.")
    ap.add_argument("--apply", action="store_true", help="actually delete (default: dry run)")
    ap.add_argument("--keep", nargs="*", default=None, metavar="ID")
    ap.add_argument("--reject", nargs="*", default=None, metavar="ID")
    ap.add_argument("--reject-pending", action="store_true",
                    help="treat every still-unreviewed id as rejected")
    args = ap.parse_args()

    if args.keep:
        print(f"marked {set_status(args.keep, 'approved')} approved")
    if args.reject:
        print(f"marked {set_status(args.reject, 'rejected')} rejected")

    reg = load()
    items = reg["items"]
    if not items:
        print("registry empty — nothing this domain generated is tracked yet")
        return

    refs = referenced_ids()
    doomed, kept = [], []
    for tid, meta in items.items():
        st = meta.get("status", "pending")
        if st == "approved":
            kept.append((tid, "approved")); continue
        if tid in refs:
            kept.append((tid, "referenced in the repo")); continue
        if st == "rejected" or (args.reject_pending and st == "pending"):
            doomed.append((tid, meta))
        else:
            kept.append((tid, "pending review"))

    print(f"\nregistry: {len(items)} ids generated by tiles 3.0")
    for tid, why in kept:
        print(f"  KEEP   {tid}  ({why})")
    print()
    if not doomed:
        print("nothing to delete")
        return
    client = PixelLabClient()
    for tid, meta in doomed:
        if not args.apply:
            print(f"  would delete {tid}  {meta.get('purpose','')} :: {meta.get('prompt','')[:60]}")
            continue
        try:
            client._request("DELETE", f"/tiles-pro/{tid}")
            items[tid]["status"] = "deleted"
            items[tid]["deleted_at"] = _now()
            print(f"  deleted {tid}")
        except PixelLabError as e:
            print(f"  ! failed {tid}: {str(e)[:120]}")
    if args.apply:
        save(reg)
    else:
        print(f"\n{len(doomed)} would be deleted. Re-run with --apply to do it.")


if __name__ == "__main__":
    main()
