#!/usr/bin/env node
// Builds the two generated files of the domain FROM THE LIBRARY ON DISK:
//
//   shaders/library/index.js   one import per effect file (what the viewer and
//                               the game import)
//   shaders/shaders.json        the catalog: every effect's metadata, no code
//                               (what the wiki lists and a tooltip reads)
//
//   node shaders/pipeline/catalog.mjs           write both
//   node shaders/pipeline/catalog.mjs --check   exit 1 if either is stale
//
// Every definition is imported and validated (defineEffect throws on a
// malformed one), and every id must equal its file path: fire/fireball lives
// in library/fire/fireball.js, so a feedback key is always a real file.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOMAIN = resolve(HERE, "..");
const LIB = join(DOMAIN, "library");
const CHECK = process.argv.includes("--check");

async function files() {
  const out = [];
  for (const fam of (await readdir(LIB, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
    if (!fam.isDirectory() || fam.name.startsWith("_")) continue;
    for (const f of (await readdir(join(LIB, fam.name))).sort()) if (f.endsWith(".js")) out.push(`${fam.name}/${f}`);
  }
  return out;
}

const fnDesc = (v) => (typeof v === "function" ? "by level" : v);

async function main() {
  const list = await files();
  const { FAMILIES, KIND_LABEL } = await import(pathToFileURL(join(LIB, "families.js")).href);
  const entries = [];
  const problems = [];
  for (const rel of list) {
    const mod = await import(pathToFileURL(join(LIB, rel)).href);
    const d = mod.default;
    const want = rel.replace(/\.js$/, "");
    if (!d || d.id !== want) {
      problems.push(`${rel}: id "${d && d.id}" must be "${want}"`);
      continue;
    }
    if (!FAMILIES[d.family]) problems.push(`${rel}: family "${d.family}" is not in library/families.js`);
    if (!d.thinking || d.thinking.length < 120) problems.push(`${rel}: "thinking" must explain the design (>= 120 chars)`);
    if (!d.levels) problems.push(`${rel}: "levels" must say what changes from 1 to 10`);
    const s = { level: 5, lv: 4 / 9, tune: Object.fromEntries(Object.entries(d.tune).map(([k, v]) => [k, v.def])) };
    entries.push({
      id: d.id,
      key: `shaders/library/${d.id}`,
      file: `shaders/library/${rel}`,
      name: d.name,
      kind: d.kind,
      kindLabel: KIND_LABEL[d.kind],
      family: d.family,
      category: d.category,
      tags: d.tags,
      thinking: d.thinking,
      levels: d.levels,
      speed: d.kind === "projectile" ? { cellsPerSecondAtLevel5: +(typeof d.speed === "function" ? d.speed(s) : d.speed ?? 10).toFixed(2) } : undefined,
      events: { projectile: ["release", "impact", "end"], melee: ["hit", "end"], chain: ["hop", "end"], burst: ["peak", "end"] }[d.kind] || ["start", "end"],
      sustained: ["beam", "aura", "zone", "screen"].includes(d.kind),
      radius: d.radius === undefined ? undefined : fnDesc(d.radius),
      planes: [...new Set(d.layers.map((L) => L.plane))],
      light: !!d.light,
      layers: d.layers.map((L) => ({ id: L.id, plane: L.plane, emissive: L.emissive !== false })),
      tune: d.tune,
    });
  }
  if (problems.length) {
    console.error(problems.join("\n"));
    process.exit(1);
  }
  const index =
    "// GENERATED by shaders/pipeline/catalog.mjs — do not edit by hand.\n" +
    "// Every effect in the library, one import per file, in catalog order.\n" +
    list.map((rel, i) => `import e${i} from "./${rel}";`).join("\n") +
    `\n\nexport const LIBRARY = [${list.map((_, i) => `e${i}`).join(", ")}];\nexport default LIBRARY;\n`;
  const catalog =
    JSON.stringify(
      {
        format: "nangijala-shaders-catalog@1",
        runtime: "shaders/runtime/index.js",
        viewer: "shaders/viewer/index.html",
        families: FAMILIES,
        count: entries.length,
        effects: entries,
      },
      null,
      1,
    ) + "\n";
  const targets = [
    [join(LIB, "index.js"), index],
    [join(DOMAIN, "shaders.json"), catalog],
  ];
  let stale = 0;
  for (const [path, text] of targets) {
    let cur = null;
    try {
      cur = await readFile(path, "utf8");
    } catch {}
    if (cur === text) continue;
    stale++;
    if (CHECK) console.error(`stale: ${path} (run node shaders/pipeline/catalog.mjs)`);
    else await writeFile(path, text);
  }
  if (CHECK && stale) process.exit(1);
  console.log(`${entries.length} effects${CHECK ? " (catalog up to date)" : stale ? " (written)" : " (unchanged)"}`);
}

main().catch((e) => {
  console.error(e.stack || e);
  process.exit(1);
});
