import Phaser from "phaser";
import { loadManifest } from "./manifest";
import { withFallback } from "./placeholder";
import { chooseCharacter } from "./select";
import { WorldScene } from "./scenes/WorldScene";
import { loadWorld, loadWorldsList } from "./maps";
import { buildDemoWorld } from "@nangijala/shared";
import { MapPreviewScene } from "./scenes/MapPreviewScene";
import { setLoadingProgress, showLoading } from "./loading";

// ---- PWA ----
// Capture the browser's install prompt the moment it fires (often before any
// UI exists) so the select screen can offer an "Install app" button
// (Android home screen). Registered at module scope on purpose.
window.addEventListener("beforeinstallprompt", (e) => {
  e.preventDefault();
  (window as any).__mlInstall = e;
  window.dispatchEvent(new Event("ml-can-install"));
});
// The service worker exists only for installability — it caches nothing
// (see public/sw.js). Dev stays SW-free so vite HMR is never in its path.
if (import.meta.env.PROD && "serviceWorker" in navigator) {
  navigator.serviceWorker.register("/sw.js").catch(() => {});
}
// Block pinch-zoom in ALL modes. Under "Desktop site" the viewport meta
// (user-scalable=no included) is ignored, so CSS touch-action (index.html)
// plus these listeners are what actually enforce it: kill any multi-touch
// move before the browser turns it into a page zoom, and iOS's proprietary
// gesture events for good measure. Single-finger input (taps, list
// scrolling) is untouched.
document.addEventListener(
  "touchmove",
  (e) => {
    if (e.touches.length > 1) e.preventDefault();
  },
  { passive: false },
);
document.addEventListener("gesturestart", (e) => e.preventDefault());
// Portrait-only (for now): the manifest locks the installed app; in-browser
// the lock API only works in fullscreen contexts, so it's best-effort (the
// #ml-rotate CSS overlay in index.html covers plain browser landscape).
if (window.matchMedia("(display-mode: standalone), (display-mode: fullscreen)").matches) {
  (screen.orientation as unknown as { lock?: (o: string) => Promise<void> }).lock?.("portrait")
    .catch(() => {});
}

async function bootMapPreview(): Promise<boolean> {
  if (location.hash !== "#map") return false;
  const world = await loadWorld();
  if (!world) {
    document.body.innerHTML =
      '<p style="color:#eef;font-family:monospace;padding:2rem">No map yet ' +
      "(pixel/maps/world/world.json not found).</p>";
    return true;
  }
  const game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: "game",
    backgroundColor: "#12121c",
    pixelArt: true,
    scale: { mode: Phaser.Scale.RESIZE, width: window.innerWidth, height: window.innerHeight },
    scene: [MapPreviewScene],
  });
  game.registry.set("world", world);
  return true;
}

/** Tiny build-version badge so testers can tell which deploy they're running. */
function showVersion() {
  const sha = (import.meta.env.VITE_GIT_SHA as string | undefined) || "dev";
  console.log(`[nangijala] build ${sha}`);
  const el = document.createElement("div");
  el.textContent = sha.slice(0, 7);
  el.style.cssText =
    "position:fixed;left:6px;bottom:4px;z-index:50;font:11px monospace;color:#8890b3;" +
    "opacity:.7;pointer-events:none;user-select:none";
  document.body.appendChild(el);
}

/** Poll /version and offer a one-click reload when a newer deploy is live. */
function watchForUpdates() {
  const mine = (import.meta.env.VITE_GIT_SHA as string | undefined) || "dev";
  if (mine === "dev") return; // local dev: vite HMR handles it
  const check = async () => {
    try {
      const res = await fetch("/version", { cache: "no-store" });
      if (!res.ok) return;
      const { sha } = (await res.json()) as { sha: string };
      if (sha && sha !== "dev" && sha !== mine) showUpdateBanner(sha);
    } catch {}
  };
  setInterval(check, 60_000);
}

let updateBannerShown = false;
function showUpdateBanner(sha: string) {
  if (updateBannerShown) return;
  updateBannerShown = true;
  const el = document.createElement("div");
  el.textContent = `⬆ New version ${sha.slice(0, 7)} — click to reload`;
  el.style.cssText =
    "position:fixed;top:10px;left:50%;transform:translateX(-50%);z-index:100;cursor:pointer;" +
    "padding:8px 16px;border-radius:8px;background:#5a7bd6;color:#fff;font:14px system-ui,sans-serif;" +
    "box-shadow:0 4px 16px #0007";
  el.addEventListener("click", () => location.reload());
  document.body.appendChild(el);
}

/** Per-variant tile art bases (client/public/tile-bases.json, generated by
 * scripts/build-tile-bases.mjs at manifest time) — how deep each variant's
 * drawn content reaches, so tall art can be grounded exactly. Null when the
 * file is missing; the scenes fall back to the old imgH-64 lift. */
async function loadTileBases(): Promise<unknown> {
  try {
    const res = await fetch("/tile-bases.json");
    if (res.ok) return await res.json();
  } catch {}
  return null;
}

async function boot() {
  showVersion();
  watchForUpdates();
  if (await bootMapPreview()) return;
  const manifest = await loadManifest();
  // The art agents periodically reset/regenerate the roster, so it can be empty.
  // Never dead-end the player: fall back to a built-in "Wanderer" so the shared
  // world is always joinable (the world scene draws it procedurally).
  manifest.characters = withFallback(manifest.characters);

  // The EMISSION DEMO (/#emission or [0] in game) is the REAL game on a
  // generated station world: same renderer, same server-authoritative
  // movement, same night pipeline — what you test there is what the game
  // does. The world is built deterministically from the same registries the
  // server reads, so client and server hold the identical grid.
  const demoMode = location.hash === "#emission";
  const tileBases = await loadTileBases();

  // Pre-join screen. Demo mode fixes the world (the generated station), so it
  // only picks a character; otherwise the player chooses BOTH a world (any
  // playable maps2 world the maps agent has shipped) AND a character.
  const worlds = demoMode ? [] : await loadWorldsList();

  // Dead-connection rejoin fast path: WorldScene sets ml-rejoin before its
  // recovery reload — skip the select screen and re-enter with the remembered
  // choice, so a phone coming back from background is in the world within
  // seconds (position restored server-side via the token store).
  let choice: Awaited<ReturnType<typeof chooseCharacter>> | null = null;
  if (!demoMode && sessionStorage.getItem("ml-rejoin") === "1") {
    sessionStorage.removeItem("ml-rejoin");
    try {
      const saved = JSON.parse(localStorage.getItem("ml-last-choice") || "null") as {
        world?: string;
        characterUid?: string;
        name?: string;
      } | null;
      const character = manifest.characters.find((c) => c.uid === saved?.characterUid);
      const worldOk = worlds.length === 0 || worlds.some((w) => w.name === saved?.world);
      if (saved?.world && character && worldOk) {
        showLoading();
        choice = { world: saved.world, character, name: saved.name || "wanderer" };
      }
    } catch {}
  }
  const { world: worldName, character, name } = choice ?? (await chooseCharacter(manifest, worlds));

  // select.ts showed the loading overlay on commit; the world JSON is the
  // first slow step (a few MB on mobile), then WorldScene.preload takes over
  // the progress bar with the actual asset counts.
  setLoadingProgress(0.05, "Fetching world…");
  let world: Awaited<ReturnType<typeof loadWorld>>;
  if (demoMode) {
    let emission: Record<string, never> = {};
    try {
      const res = await fetch("/assets/tiles/emission.json");
      if (res.ok) emission = ((await res.json()) as { categories?: never }).categories ?? {};
    } catch {}
    world = buildDemoWorld(emission, tileBases as Parameters<typeof buildDemoWorld>[1]);
  } else {
    // The chosen isometric world (null if its world.json is missing; the world
    // scene then falls back to a plain ground).
    world = await loadWorld(worldName);
  }

  const game = new Phaser.Game({
    type: Phaser.AUTO,
    parent: "game",
    backgroundColor: "#12121c",
    pixelArt: true,
    scale: {
      mode: Phaser.Scale.RESIZE,
      width: window.innerWidth,
      height: window.innerHeight,
    },
    scene: [WorldScene],
  });

  game.registry.set("manifest", manifest);
  game.registry.set("character", character);
  game.registry.set("name", name);
  game.registry.set("world", world);
  game.registry.set("worldName", worldName);
  game.registry.set("tileBases", tileBases);
  game.registry.set("demoMode", demoMode);
}

boot();
