/**
 * The composer's own TITLE THEME (games2/composer/music/): a full music track
 * generated by the composer (ElevenLabs Music, same rights as the music
 * domain — music/pipeline) for the character-select screen. Bundled straight
 * into the client by Vite (like the foley), so no asset routes. mp3 on
 * purpose — decodeAudioData handles it in every browser incl. Safari/iOS
 * (ogg/opus does not). Empty until the theme is generated → startTitleTheme
 * is a graceful no-op.
 */

// music/*.mp3 → hashed bundle URLs.
const files = import.meta.glob("../music/*.mp3", {
  query: "?url",
  import: "default",
  eager: true,
}) as Record<string, string>;

/** The bundled title-theme URL, or null if the composer has not generated a
 * theme yet. Prefers a file named like `*title*`, else the first mp3. */
export function titleThemeUrl(): string | null {
  const keys = Object.keys(files).sort();
  const key = keys.find((k) => /title|theme/i.test(k)) ?? keys[0];
  return key ? files[key] : null;
}
